[target.aarch64-linux-android]
linker = "/opt/android/ndk/r29/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"
ar = "/opt/android/ndk/r29/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
